### ISSUE TITLE
Figure caption is hard to distinguish from body text

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#161]
The caption text is styled the same as the body text. This makes for a confusing reading experience.

We should come up with a style that distinguishes the caption text visually from the body text. Also, it would be more readable to have a bit of whitespace between the figure and the image. 

Also, it looks odd to me that the figure text is wider than the image/figure. 

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/24797493/163828161-51bbeea1-994e-40e9-982a-903d9f522138.png">

This may be a good place to reuse the gray from the page content TOC.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/24797493/163829743-290aa2c9-04d6-4d09-8b2c-08be177091a7.png">

**Comment by PaarthAgarwal** [comment]
I'll give it a try

**Comment by PaarthAgarwal** [comment]
@tbrlpld I looked into it. Turns out there were some minor errors in [_component_figure.scss](https://github.com/wagtail/sphinx_wagtail_theme/blob/main/sass/_component_figure.scss). After the fix it looks like this:
![image](https://user-images.githubusercontent.com/86092410/166671536-ae76d063-11e3-488e-9dbb-f79ecb396f16.png)
The italic style was default but let me know if you want to drop it.

**Comment by PaarthAgarwal** [comment]
Based on the discussion here https://github.com/wagtail/sphinx_wagtail_theme/issues/78#issuecomment-1087993428, I'm dropping italicized text.
