### ISSUE TITLE
Stable version of our sphinx documentation appears to be broken

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/sphinx_wagtail_theme#212]
Stable version of the wagtail sphinx documentation appears to be broken. The styles aren't showing up. Maybe JS broke too.

![image](https://user-images.githubusercontent.com/86092410/191478373-63051a6e-56da-4519-af54-cf0b9488fa0d.png)

**Comment by thibaudcolas** [comment]
Nice catch @PaarthAgarwal! I have disabled this version in the Read the Docs admin because I don’t think it’s worthwhile for us to support it. For the theme to display correctly, we need its front-end build to run, which isn’t possible directly in the Read the Docs builds. So we technically deploy from a `gh-pages` branch, with the compiled styles & JS committed. 

This is how `latest` works – and we’d have to create another branch to build `stable` if we wanted an auto-updating "most recent stable release" version. Feels like a lot of work. 

I’ll close this now but we can re-open if others think it’s worthwhile.
