### ISSUE TITLE
Clean up layout.html

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#5]
`sphinx_typo3_theme/layout.html` is the 'base template' and contains things we don't want/need:

- [x] Typo3 specific headers / footers / blocks
- [x] Vanilla CSS, we should use Bootstrap
- [x] Redundant comment (all comments)
- [ ] Head should at least have the current RTD-theme features

Let us keep this issue as meta-issue and open multiple

**Comment by tbrlpld** [comment]
**Thought** @allcaps I am just wondering if the proposed design (#10) lends itself to implementation with Bootstrap. Otherwise we are going to be fighting Bootstrap and trying to override its styles (which I guess was the kind of thing we wanted to avoid with going for a custom theme). 

To still get the benefit of the pre-made utilities, we could consider something like [Tailwind](https://tailwindcss.com/).

**Comment by tbrlpld** [comment]
Just noticed that Bootstrap is already bundled with the theme. It's just not used that much.
