### ISSUE TITLE
Do we need "next" and "previous" links?

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#87]
They currently have the default bootstrap style, which does not look very good. 

I honestly never really use them. 

Just wondering what your thoughts are?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/24797493/114140901-949c4c00-98ac-11eb-8e1e-f06d79abfc02.png">

**Comment by Stormheg** [comment]
I agree the styling doesn't look very nice. Depending of the length of the link it feels off...

Wouldn't mind not having next and previous links but curious how other people feel about this.

**Comment by tbrlpld** [comment]
On reconsideration,  I could see this being useful when something like the tutorial is split into multiple pages (which I think it should). 

The styling should definitely be changed though. 

I could see separate buttons (more borders) with space between, instead of them pushed together in the centre. I feel like I have seen that on plenty other docs pages.

**Comment by vsalvino** [comment]
I would keep them, they are especially useful for tutorial or multi-step docs.

For design, simple left/right aligned blocks with arrows seems to be readable:

(From coderedcms docs)
![image](https://user-images.githubusercontent.com/13453401/142920803-208fbe32-5842-4288-995a-79d53fff4191.png)


(From my sphinx-library theme):
![image](https://user-images.githubusercontent.com/13453401/142920742-e3d3f005-68d5-4fcc-909b-ee4f893dc1b7.png)

I would be happy to make a PR since I am familiar with the code for doing this.

**Comment by tbrlpld** [comment]
This has been on my list for so long. It always annoys me when looking at the new theme since this does not really seem to fit the style either. 

@vsalvino this is exactly the style I had in mind too. Happy for you to go along with this 👍

**Comment by tbrlpld** [comment]
Closed via #129
