### ISSUE TITLE
Max width for sidebar (main navigation)

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#99]
Currently, the width of the sidebar (main navigation) increases indefinitely. 

This should be limited to some sensible value to make the layout work nicer on larger screens.

**Comment by tbrlpld** [comment]
This must be possible with Bootstrap, because that is how their documentation works:
<img width="2132" alt="image" src="https://user-images.githubusercontent.com/24797493/115169827-d79fb180-a05a-11eb-9332-f992af8dc970.png">

**Comment by PaarthAgarwal** [comment]
So currently, the sidebar is set to occupy 3/13 screen width on screen sizes large and above because of `col-lg-3` class in our documentation.
Bootstrap uses `col-md-3` and  `col-xl-2` classes i.e 3/12 screen width for medium above and 2/12 screen width for xl above. 
Should we do the same, or should we set `max-width` with some arbitrary value?
PS: Tried the way bootstrap did it. Won't call it an improvement over the current design.
